services:
  server:
    image: node:12-alpine
    working_dir: '/app'
    command: 'npm run start'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:8
    # container 가 제거되어도 데이터를 유지할 때 사용합니다.
    #    volumes:
    #      - ./ignored/database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'test'
      TZ: 'Asia/Seoul'
    ports:
      - '3307:3306'
